### PR TITLE
Update to use new Petabridge library template

### LINKED ISSUE #23: Deprecate Akka.TestKit.NUnit (NUnit 2.x) package
NUnit 3 was released about 2 years ago, and now it supports .Net Core. It is a good time to stop support NUnit 2 package

### PR DESCRIPTION
**Pull request by ayoung**
Closes #23 
Replaces #22

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Ah, looks like we're going to need to replace the test runner inside the FAKE file from XUnit to NUnit

**Comment by ayoung** [comment]
Is this easy to do? Not familiar with F# and Fake.

**Comment by ayoung** [comment]
Damn it.

**Comment by alexvaluyskiy** [comment]
@ayoung you should also remove `Akka.TestKit.NUnit3.nuspec` and `packages.config`

**Comment by Aaronontheweb** [comment]
@ayoung the current FAKE script in the dev branch should give you what you need to do it. Otherwise I can help with this once I get some cycles back.

**Comment by Danthar** [comment]
Closed via #26

**Pull request closed without merging**
