### PR TITLE
Modernize repository

### PR DESCRIPTION
**Pull request by Arkatufus**
* Update common.props
* Add Azure Pipelines CI/CD script

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
I'll update the CI system to use AzDo

**Comment by Aaronontheweb** [comment]
I'll need to add this back onto my to-do list; lost track over the holidays

**Comment by swimmesberger** [comment]
@Aaronontheweb are there any plans to further support nunit? We unfortunately can't switch to xunit atm

**Comment by Aaronontheweb** [comment]
@swimmesberger yep, we're modernizing the repo now https://github.com/akkadotnet/Akka.TestKit.NUnit/pull/47

**Pull request closed without merging**
